CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela Clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    empresa TEXT,
    email TEXT,
    status TEXT DEFAULT 'ativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 1. Tabela de Perfis (Cria apenas se não existir)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    role TEXT CHECK (role IN ('super_admin', 'financeiro', 'gestor_trafego', 'social_media', 'colaborador')) DEFAULT 'colaborador',
    tenant_id BIGINT REFERENCES public.clientes(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Segurança (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso (Removemos as antigas para evitar duplicidade e recriamos)
DROP POLICY IF EXISTS "Usuários podem ver seu próprio perfil" ON public.profiles;
CREATE POLICY "Usuários podem ver seu próprio perfil" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Super Admins veem todos os perfis" ON public.profiles;
CREATE POLICY "Super Admins veem todos os perfis" ON public.profiles
    FOR SELECT USING (
        auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'super_admin')
    );

-- Função para criar perfil automaticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role, tenant_id)
    VALUES (
        new.id, 
        new.email, 
        new.raw_user_meta_data->>'full_name', 
        'colaborador',
        CASE
            WHEN (new.raw_user_meta_data->>'tenant_id') ~ '^\d+$' THEN (new.raw_user_meta_data->>'tenant_id')::bigint
            WHEN (new.raw_user_meta_data->>'cliente_id') ~ '^\d+$' THEN (new.raw_user_meta_data->>'cliente_id')::bigint
            ELSE NULL
        END
    )
    ON CONFLICT (id) DO NOTHING; -- Se já existir, não faz nada
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger (Gatilho)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Tabelas de Negócio (Com verificação IF NOT EXISTS)

-- Tabela Financeiro
CREATE TABLE IF NOT EXISTS public.financeiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    tipo TEXT CHECK (tipo IN ('entrada', 'saida')) NOT NULL,
    categoria TEXT,
    data_transacao DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela Projetos
CREATE TABLE IF NOT EXISTS public.projetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id),
    status TEXT DEFAULT 'em_andamento',
    prazo DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela Memberships (Painel do Cliente)
CREATE TABLE IF NOT EXISTS public.memberships (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    tenant_id BIGINT REFERENCES public.clientes(id),
    role TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS memberships_user_id_idx ON public.memberships (user_id);
CREATE INDEX IF NOT EXISTS memberships_tenant_id_idx ON public.memberships (tenant_id);
CREATE INDEX IF NOT EXISTS memberships_user_tenant_idx ON public.memberships (user_id, tenant_id);
