DO $$
DECLARE
  post_id_type text;
BEGIN
  SELECT data_type INTO post_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'social_posts'
    AND column_name = 'id';

  IF post_id_type IS NULL THEN
    RAISE EXCEPTION 'social_posts.id_not_found';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'social_approvals'
  ) THEN
    IF post_id_type = 'uuid' THEN
      EXECUTE $sql$
        CREATE TABLE public.social_approvals (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_id uuid NOT NULL,
          status_anterior text,
          status_novo text,
          action_type text,
          comment text,
          actor_user_id uuid,
          created_at timestamptz NOT NULL DEFAULT now()
        )
      $sql$;
    ELSIF post_id_type IN ('bigint', 'integer', 'smallint') THEN
      EXECUTE format($sql$
        CREATE TABLE public.social_approvals (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_id %s NOT NULL,
          status_anterior text,
          status_novo text,
          action_type text,
          comment text,
          actor_user_id uuid,
          created_at timestamptz NOT NULL DEFAULT now()
        )
      $sql$, post_id_type);
    ELSE
      EXECUTE $sql$
        CREATE TABLE public.social_approvals (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_id text NOT NULL,
          status_anterior text,
          status_novo text,
          action_type text,
          comment text,
          actor_user_id uuid,
          created_at timestamptz NOT NULL DEFAULT now()
        )
      $sql$;
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  post_id_type text;
BEGIN
  SELECT data_type INTO post_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'social_posts'
    AND column_name = 'id';

  IF post_id_type IS NULL THEN
    RAISE EXCEPTION 'social_posts.id_not_found';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'social_approvals'
      AND column_name = 'post_id'
  ) THEN
    IF post_id_type = 'uuid' THEN
      EXECUTE 'ALTER TABLE public.social_approvals ADD COLUMN post_id uuid';
    ELSIF post_id_type IN ('bigint', 'integer', 'smallint') THEN
      EXECUTE format('ALTER TABLE public.social_approvals ADD COLUMN post_id %s', post_id_type);
    ELSE
      EXECUTE 'ALTER TABLE public.social_approvals ADD COLUMN post_id text';
    END IF;
  END IF;
END $$;

ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS status_anterior text;
ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS status_novo text;
ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS action_type text;
ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS comment text;
ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS actor_user_id uuid;
ALTER TABLE public.social_approvals ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS social_approvals_post_created_idx
ON public.social_approvals (post_id, created_at DESC);

ALTER TABLE public.social_approvals ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.social_approvals TO authenticated;

DROP POLICY IF EXISTS "Agency users can read social approvals" ON public.social_approvals;
CREATE POLICY "Agency users can read social approvals"
ON public.social_approvals
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.colaboradores col
    WHERE col.user_id = auth.uid()
  )
);

CREATE OR REPLACE FUNCTION public.log_social_post_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  old_status text;
  new_status text;
  action text;
  comment_text text;
BEGIN
  IF TG_OP <> 'UPDATE' THEN
    RETURN NEW;
  END IF;

  old_status := to_jsonb(OLD)->>'status';
  new_status := to_jsonb(NEW)->>'status';

  IF old_status IS NOT DISTINCT FROM new_status THEN
    RETURN NEW;
  END IF;

  comment_text := NULLIF(COALESCE(
    to_jsonb(NEW)->>'comentario_cliente',
    to_jsonb(NEW)->>'feedback_aprovacao',
    to_jsonb(NEW)->>'feedback_ajuste',
    (to_jsonb(NEW)->'feedback_cliente'->>'comentario')
  ), '');

  IF new_status IN ('ready_for_approval', 'awaiting_approval') THEN
    action := 'submit_for_approval';
  ELSIF new_status = 'approved' THEN
    action := 'approve';
  ELSIF new_status = 'changes_requested' THEN
    action := 'request_changes';
  ELSIF new_status = 'rejected' THEN
    action := 'reject';
  ELSIF new_status IN ('draft', 'briefing_sent', 'design_in_progress', 'in_production', 'producing')
    AND old_status IN ('ready_for_approval', 'awaiting_approval', 'approved', 'changes_requested', 'rejected')
  THEN
    action := 'return_to_review';
  ELSE
    action := 'status_change';
  END IF;

  INSERT INTO public.social_approvals (
    post_id,
    status_anterior,
    status_novo,
    action_type,
    comment,
    actor_user_id,
    created_at
  )
  VALUES (
    NEW.id,
    old_status,
    new_status,
    action,
    comment_text,
    auth.uid(),
    now()
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS social_posts_audit_status_change ON public.social_posts;
CREATE TRIGGER social_posts_audit_status_change
AFTER UPDATE OF status ON public.social_posts
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION public.log_social_post_status_change();
