DO $$
DECLARE
  calendar_id_type text;
BEGIN
  SELECT data_type INTO calendar_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'social_calendars'
    AND column_name = 'id';

  IF calendar_id_type IS NULL THEN
    RAISE EXCEPTION 'social_calendars.id_not_found';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'social_calendar_items'
  ) THEN
    EXECUTE format($sql$
      CREATE TABLE public.social_calendar_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        calendar_id %s NOT NULL REFERENCES public.social_calendars(id) ON DELETE CASCADE,
        data date NOT NULL,
        tema text NOT NULL,
        tipo_conteudo text NOT NULL DEFAULT 'post_estatico',
        canal text NOT NULL DEFAULT 'instagram',
        observacoes text,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    $sql$, calendar_id_type);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS social_calendar_items_calendar_date_idx
ON public.social_calendar_items (calendar_id, data);

ALTER TABLE public.social_posts
ADD COLUMN IF NOT EXISTS calendar_item_id bigint;

ALTER TABLE public.social_posts
ADD COLUMN IF NOT EXISTS plataforma text;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'social_posts'
      AND column_name = 'calendar_item_id'
  ) THEN
    BEGIN
      ALTER TABLE public.social_posts
      ADD CONSTRAINT social_posts_calendar_item_fk
      FOREIGN KEY (calendar_item_id)
      REFERENCES public.social_calendar_items(id)
      ON DELETE SET NULL;
    EXCEPTION
      WHEN duplicate_object THEN
        NULL;
    END;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS social_posts_calendar_item_id_uniq
ON public.social_posts (calendar_item_id)
WHERE calendar_item_id IS NOT NULL;
