
-- SCRIPT DE CORREÇÃO E ATUALIZAÇÃO DO BANCO DE DADOS
-- Execute este script no SQL Editor do Supabase para corrigir as tabelas e ativar as automações.

-- 1. GARANTIR QUE AS TABELAS EXISTAM

-- Tabela de Configurações (White Label)
CREATE TABLE IF NOT EXISTS public.configuracoes (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;
-- Permitir leitura pública ou autenticada (para carregar tema no login)
CREATE POLICY "Leitura de Configurações" ON public.configuracoes FOR SELECT USING (true);
-- Permitir escrita apenas para autenticados (ou admins, mas aqui deixamos autenticados para facilitar)
CREATE POLICY "Escrita de Configurações" ON public.configuracoes FOR ALL USING (auth.role() = 'authenticated');


-- Tabela de Clientes (Base) - Caso não exista
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_empresa TEXT,
    nome_fantasia TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de Perfis (Profiles) - Espelho de Auth.Users
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    nome TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'user',
    tenant_id BIGINT REFERENCES public.clientes(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger para criar Profile automaticamente ao criar User
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nome, tenant_id)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    CASE
      WHEN (new.raw_user_meta_data->>'tenant_id') ~ '^\d+$' THEN (new.raw_user_meta_data->>'tenant_id')::bigint
      WHEN (new.raw_user_meta_data->>'cliente_id') ~ '^\d+$' THEN (new.raw_user_meta_data->>'cliente_id')::bigint
      ELSE NULL
    END
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Tabela de Lembretes/Notificações
CREATE TABLE IF NOT EXISTS public.lembretes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    concluido BOOLEAN DEFAULT false,
    user_id UUID REFERENCES auth.users(id), -- NULL = Público/Todos
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de Tarefas
CREATE TABLE IF NOT EXISTS public.tarefas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    titulo TEXT NOT NULL,
    descricao TEXT,
    status TEXT DEFAULT 'pendente',
    prazo_tipo TEXT CHECK (prazo_tipo IN ('para_dia', 'ate_dia')),
    prazo_data TIMESTAMP WITH TIME ZONE,
    tipo TEXT DEFAULT 'tarefa' CHECK (tipo IN ('tarefa', 'reuniao')),
    horario_reuniao TIME,
    criado_por UUID REFERENCES auth.users(id),
    cliente_id BIGINT REFERENCES public.clientes(id),
    time_id UUID REFERENCES public.times(id),
    post_id UUID REFERENCES public.social_posts(id), -- Link com Social Media
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de Atribuições (Quem faz a tarefa)
CREATE TABLE IF NOT EXISTS public.tarefa_atribuicoes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tarefa_id UUID REFERENCES public.tarefas(id) ON DELETE CASCADE,
    usuario_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de Histórico da Tarefa
CREATE TABLE IF NOT EXISTS public.tarefa_historico (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tarefa_id UUID REFERENCES public.tarefas(id) ON DELETE CASCADE,
    usuario_id UUID REFERENCES auth.users(id),
    tipo TEXT NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. ATUALIZAR COLUNAS (Caso as tabelas já existam mas faltem colunas)

DO $$
BEGIN
    -- Adicionar post_id em tarefas se não existir
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tarefas' AND column_name='post_id') THEN
        ALTER TABLE public.tarefas ADD COLUMN post_id UUID REFERENCES public.social_posts(id);
    END IF;

    -- Adicionar user_id em lembretes se não existir
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='lembretes' AND column_name='user_id') THEN
        ALTER TABLE public.lembretes ADD COLUMN user_id UUID REFERENCES auth.users(id);
    END IF;
END $$;

-- 3. PERMISSÕES (RLS)

ALTER TABLE public.tarefas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tarefa_atribuicoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tarefa_historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lembretes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;

-- Limpar policies antigas para recriar
DROP POLICY IF EXISTS "Acesso total a tarefas" ON public.tarefas;
DROP POLICY IF EXISTS "Acesso total a atribuicoes" ON public.tarefa_atribuicoes;
DROP POLICY IF EXISTS "Acesso total a historico" ON public.tarefa_historico;
DROP POLICY IF EXISTS "Acesso Total Lembretes" ON public.lembretes;
DROP POLICY IF EXISTS "Ver Lembretes Proprios ou Publicos" ON public.lembretes;
DROP POLICY IF EXISTS "Gerenciar Lembretes Proprios" ON public.lembretes;
DROP POLICY IF EXISTS "Publico pode atualizar posts em aprovação" ON public.social_posts;
DROP POLICY IF EXISTS "Publico pode ver posts em aprovação" ON public.social_posts;
DROP POLICY IF EXISTS "Acesso autenticado posts" ON public.social_posts;

-- Criar novas policies permissivas para operação
CREATE POLICY "Acesso total a tarefas" ON public.tarefas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acesso total a atribuicoes" ON public.tarefa_atribuicoes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acesso total a historico" ON public.tarefa_historico FOR ALL USING (auth.role() = 'authenticated');

-- Policies de Lembretes (Ver seus ou públicos)
CREATE POLICY "Ver Lembretes Proprios ou Publicos" ON public.lembretes FOR SELECT TO authenticated USING (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY "Gerenciar Lembretes Proprios" ON public.lembretes FOR ALL TO authenticated USING (user_id = auth.uid() OR user_id IS NULL);

-- Policies de Social Posts (Permitir update público para aprovação externa)
CREATE POLICY "Publico pode atualizar posts em aprovação" ON public.social_posts FOR UPDATE TO public USING (approval_group_id IS NOT NULL);
-- Permitir SELECT público se tiver approval_group_id (ESSENCIAL PARA A TELA DE APROVAÇÃO)
CREATE POLICY "Publico pode ver posts em aprovação" ON public.social_posts FOR SELECT TO public USING (approval_group_id IS NOT NULL);
-- Manter acesso autenticado para posts
CREATE POLICY "Acesso autenticado posts" ON public.social_posts FOR ALL TO authenticated USING (true);


-- 4. AUTOMAÇÃO E TRIGGERS

-- Trigger 1: Criar Tarefa de Ajuste quando Cliente pede ajuste no Post
CREATE OR REPLACE FUNCTION public.handle_post_adjustment_trigger()
RETURNS TRIGGER AS $$
DECLARE
    v_cliente_nome TEXT;
    v_tarefa_id UUID;
BEGIN
    IF NEW.status = 'ajuste_solicitado' AND OLD.status != 'ajuste_solicitado' THEN
        
        -- Tentar pegar nome do cliente
        SELECT COALESCE(nome_empresa, nome_fantasia, 'Cliente') INTO v_cliente_nome FROM public.clientes WHERE id = NEW.cliente_id;
        
        -- Criar Tarefa
        INSERT INTO public.tarefas (
            titulo,
            descricao,
            status,
            prazo_data,
            tipo,
            cliente_id,
            criado_por,
            post_id
        ) VALUES (
            'Ajuste em Post: ' || NEW.tema,
            'O cliente solicitou ajustes no post de ' || to_char(NEW.data_agendada, 'DD/MM/YYYY') || '. Feedback: ' || COALESCE(NEW.feedback_cliente->>'comentario', 'Ver detalhes no post'),
            'pendente',
            NOW() + INTERVAL '2 days',
            'tarefa',
            NEW.cliente_id,
            NULL, -- Sistema
            NEW.id
        ) RETURNING id INTO v_tarefa_id;

        -- Criar Lembrete Geral
        INSERT INTO public.lembretes (titulo, concluido, user_id) 
        VALUES ('⚠️ Ajuste solicitado pelo cliente ' || COALESCE(v_cliente_nome, 'Desconhecido') || ' no post "' || NEW.tema || '"', false, NULL);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_auto_create_adjustment_task ON social_posts;
CREATE TRIGGER trigger_auto_create_adjustment_task
AFTER UPDATE ON social_posts
FOR EACH ROW
EXECUTE FUNCTION public.handle_post_adjustment_trigger();


-- Trigger 2: Sincronizar Status Tarefa -> Post (Em Andamento -> Ajuste em Andamento)
CREATE OR REPLACE FUNCTION public.sync_task_to_post_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.post_id IS NOT NULL AND NEW.status = 'em_andamento' AND OLD.status != 'em_andamento' THEN
        UPDATE public.social_posts 
        SET status = 'ajuste_em_andamento' 
        WHERE id = NEW.post_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_sync_task_to_post ON public.tarefas;
CREATE TRIGGER trigger_sync_task_to_post
AFTER UPDATE ON public.tarefas
FOR EACH ROW
EXECUTE FUNCTION public.sync_task_to_post_status();


-- Trigger 3: Sincronizar Status Post -> Tarefa (Salvar Ajuste/Pendente -> Concluir Tarefa)
CREATE OR REPLACE FUNCTION public.sync_post_to_task_status()
RETURNS TRIGGER AS $$
BEGIN
    -- Se o post voltou para pendente (re-aprovação) vindo de um estado de ajuste
    IF NEW.status = 'pendente' AND OLD.status IN ('ajuste_solicitado', 'ajuste_em_andamento') THEN
        UPDATE public.tarefas 
        SET status = 'concluido' 
        WHERE post_id = NEW.id AND status != 'concluido';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_sync_post_to_task ON public.social_posts;
CREATE TRIGGER trigger_sync_post_to_task
AFTER UPDATE ON public.social_posts
FOR EACH ROW
EXECUTE FUNCTION public.sync_post_to_task_status();


-- Trigger 4: Notificar Criador quando Status da Tarefa muda
CREATE OR REPLACE FUNCTION public.notify_task_creator_on_status_change()
RETURNS TRIGGER AS $$
DECLARE
    v_criador_id UUID;
    v_msg TEXT;
BEGIN
    -- Se status mudou E tem criador definido
    IF NEW.status IS DISTINCT FROM OLD.status AND NEW.criado_por IS NOT NULL THEN
        v_criador_id := NEW.criado_por;
        
        IF NEW.status = 'em_andamento' THEN
            v_msg := '🚀 A tarefa "' || NEW.titulo || '" iniciou o andamento.';
        ELSIF NEW.status IN ('concluido', 'concluida') THEN
            v_msg := '✅ A tarefa "' || NEW.titulo || '" foi concluída.';
        ELSIF NEW.status = 'solicitacao_prazo' THEN
             v_msg := '⏳ Solicitação de prazo na tarefa "' || NEW.titulo || '".';
        ELSE
            RETURN NEW;
        END IF;

        INSERT INTO public.lembretes (titulo, concluido, user_id) 
        VALUES (v_msg, false, v_criador_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_notify_task_creator ON tarefas;
CREATE TRIGGER trigger_notify_task_creator
AFTER UPDATE ON tarefas
FOR EACH ROW
EXECUTE FUNCTION public.notify_task_creator_on_status_change();
