-- Atualização da tabela traffic_metrics com novos campos de detalhes do Facebook Ads
ALTER TABLE public.traffic_metrics
ADD COLUMN IF NOT EXISTS account_name TEXT,
ADD COLUMN IF NOT EXISTS campaign_name TEXT,
ADD COLUMN IF NOT EXISTS adset_id TEXT,
ADD COLUMN IF NOT EXISTS adset_name TEXT,
ADD COLUMN IF NOT EXISTS ad_id TEXT,
ADD COLUMN IF NOT EXISTS ad_name TEXT,
ADD COLUMN IF NOT EXISTS ctr DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS objective TEXT,
ADD COLUMN IF NOT EXISTS reach INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS conversion_values JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS conversions INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_per_conversion DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS created_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS frequency DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS product_views INT DEFAULT 0;
